---
application: disburser
repository: https://github.com/NUBIC/disburser.git
deployer: deploy
development:
  server_name: disburser.dev
test:
  server_name: disburser.dev
staging:
  app_host: vtfsmqdscapp1.fsm.northwestern.edu
  server_name: disburser-staging.cancer.northwestern.edu
  server_alias: disburser-staging.cancer.northwestern.edu
  cert_file: /etc/letsencrypt/live/disburser-staging.cancer.northwestern.edu/fullchain.pem
  chain_file: /etc/pki/tls/certs/disburser-staging_cancer_northwestern_edu_interm.cer
  key_file: /etc/letsencrypt/live/disburser-staging.cancer.northwestern.edu/privkey.pem
production:
  app_host: vfsmqdscapp1.fsm.northwestern.edu
  server_name: disburser.cancer.northwestern.edu
  server_alias: disburser.cancer.northwestern.edu
  cert_file: /etc/pki/tls/certs/disburser_cancer_northwestern_edu_cert.cer
  chain_file: /etc/pki/tls/certs/disburser_cancer_northwestern_edu_interm.cer
  key_file: /etc/pki/tls/private/disburser_cancer_northwestern_edu.key
support:
  recepients:
    - disburser@northwestern.edu
  sender_address: disburser@northwestern.edu
